version: '3.4'

services:
  frontend_vue:
    container_name: frontend_vue
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: /bin/sh -c "while sleep 1000; do :; done;"
    networks:
      - network1
networks:
  network1:
    name: mi_red
    external: true